# Generated by Django 4.2.7 on 2026-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_onboarding_and_financial_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
