# Generated by Django 4.2.7 on 2026-03-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0002_contribution_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="proof_of_payment",
            field=models.ImageField(
                blank=True, null=True, upload_to="proof_of_payments/"
            ),
        ),
    ]
