# Generated by Django 4.2.7 on 2026-03-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repayments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrepayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
