# Generated by Django 4.2.7 on 2026-03-14 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cooperative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="coop_logos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CooperativeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_loan_interest_rate",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "interest_calculation_type",
                    models.CharField(
                        choices=[
                            ("FLAT", "Flat Interest"),
                            ("REDUCING", "Reducing Balance"),
                            ("MONTHLY", "Monthly Interest"),
                        ],
                        default="FLAT",
                        max_length=20,
                    ),
                ),
                (
                    "loan_duration_limits_months",
                    models.IntegerField(
                        default=12, help_text="Maximum loan duration in months"
                    ),
                ),
                (
                    "penalty_rate_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Penalty percentage for late payments",
                        max_digits=5,
                    ),
                ),
                (
                    "cooperative",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="cooperatives.cooperative",
                    ),
                ),
            ],
        ),
    ]
