# Generated by Django 4.2.7 on 2026-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooperatives", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cooperativesetting",
            name="loan_duration_limits_months",
        ),
        migrations.RemoveField(
            model_name="cooperativesetting",
            name="penalty_rate_percentage",
        ),
        migrations.AddField(
            model_name="cooperative",
            name="setup_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="allow_custom_contributions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="allow_early_repayment",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="apply_early_repayment_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="contribution_type",
            field=models.CharField(
                choices=[
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("FLEXIBLE", "Flexible"),
                ],
                default="MONTHLY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="default_contribution_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="grace_period_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="loan_eligibility_type",
            field=models.CharField(
                choices=[
                    ("IMMEDIATE", "Immediate"),
                    ("HISTORY", "Based on Contribution History"),
                ],
                default="IMMEDIATE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="max_loan_amount",
            field=models.DecimalField(
                decimal_places=2, default=1000000.0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="max_loan_duration_months",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="min_contribution_months_required",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="min_loan_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="min_loan_duration_months",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="penalty_frequency",
            field=models.CharField(
                choices=[("ONETIME", "One-time"), ("RECURRING", "Recurring")],
                default="ONETIME",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="penalty_type",
            field=models.CharField(
                choices=[("FIXED", "Fixed Amount"), ("PERCENTAGE", "Percentage (%)")],
                default="FIXED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="penalty_value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="repayment_frequency",
            field=models.CharField(
                choices=[("WEEKLY", "Weekly"), ("MONTHLY", "Monthly")],
                default="MONTHLY",
                max_length=20,
            ),
        ),
    ]
