# Generated by Django 4.2.7 on 2026-03-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooperatives", "0002_onboarding_and_financial_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperativesetting",
            name="account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="savings_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Annual interest rate for savings",
                max_digits=5,
            ),
        ),
    ]
