# Generated by Django 4.2.7 on 2026-03-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooperatives", "0003_cooperativesetting_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperativesetting",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="in_app_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cooperativesetting",
            name="sms_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
