# Generated by Django 4.2.7 on 2026-03-14 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cooperatives", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "annual_price_per_member",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_members",
                    models.IntegerField(
                        blank=True, help_text="Null for unlimited", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CooperativeSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cooperative",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="cooperatives.cooperative",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
        ),
    ]
