# Generated by Django 4.2.7 on 2026-03-14 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cooperatives", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("purpose", models.TextField()),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "interest_type",
                    models.CharField(
                        choices=[
                            ("FLAT", "Flat"),
                            ("REDUCING", "Reducing"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_months", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("DEFAULTED", "Defaulted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("application_date", models.DateField(auto_now_add=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cooperative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="cooperatives.cooperative",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_number", models.IntegerField()),
                ("due_date", models.DateField()),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["month_number"],
            },
        ),
    ]
