# Generated by Django 4.2.7 on 2026-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_repaymentschedule_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="proof_of_payment",
            field=models.ImageField(blank=True, null=True, upload_to="loan_proofs/"),
        ),
    ]
